enum EventHeader {
    AuthenticationOK = 1,
    UserIsStaff = 2,
    YoutubeTv = 3,
    Pong = 4,
    InRoom = 5,
    RpStats = 6,
    AddChatlogs = 7,
    BuyItemsList = 8,
    LoadInventoryRp = 9,
    AddInventoryItemRp = 10,
    RemoveItemInventoryRp = 11,
    NotifAlert = 12,
    RpTrocStart = 13,
    RpTrocStop = 14,
    RpTrocAccepte = 15,
    RpTrocConfirme = 16,
    RpTrocUpdateItems = 17,
    NotifTop = 18,
    NotifTopInit = 19,
    SettingVolume = 20,
    PlaySound = 21,
    StopSound = 22,
    BotChoose = 23,
}

export default EventHeader;